variables:
  SOPLEX_REVISION: bugfix-70
  SCIP_REVISION: v90-bugfix
  BOOST_VERSION: 1.80.0
  MIPDD_DIR: ${CI_PROJECT_DIR}/builds/MIP-DD
  SOPLEX_DIR: /usr/local/lib/cmake/soplex
  SCIP_DIR: /usr/local/lib/cmake/scip

stages:
  - setup
  - build

setup:
  stage: setup
  image:
    name: gcc:10
  rules:
    - if: $CI_MERGE_REQUEST_TITLE =~ /^Draft:/
      when: manual
    - if: $CI_MERGE_REQUEST_ID
  before_script:
    - apt-get update
    - apt-get install -y cmake libtbb-dev
  script:
    # download, build and install boost
    - wget https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION}/source/boost_$(echo ${BOOST_VERSION} | tr . _).tar.gz
    - tar -xzf boost_$(echo ${BOOST_VERSION} | tr . _).tar.gz
    - cd boost_$(echo ${BOOST_VERSION} | tr . _)
    - ./bootstrap.sh --with-libraries=program_options,serialization,iostreams,regex
    - ./b2 -j$(nproc) install

    # clone, build and install soplex
    - git clone https://github.com/scipopt/soplex.git ${CI_PROJECT_DIR}/soplex
    - cd ${CI_PROJECT_DIR}/soplex && git checkout ${SOPLEX_REVISION}
    - mkdir -p ${CI_PROJECT_DIR}/soplex/build
    - cd ${CI_PROJECT_DIR}/soplex/build
    - cmake ..
    - make -j$(nproc) && make install

    # clone, build and install scip
    - git clone https://github.com/scipopt/scip.git ${CI_PROJECT_DIR}/scip
    - cd ${CI_PROJECT_DIR}/scip && git checkout ${SCIP_REVISION}
    - mkdir -p ${CI_PROJECT_DIR}/scip/build
    - cd ${CI_PROJECT_DIR}/scip/build
    - cmake .. -DZIMPL=off -DREADLINE=off -DGMP=off -DPAPILO=off -DIPOPT=off
    - make -j$(nproc) && make install

    - mkdir -p ${CI_PROJECT_DIR}/builds/MIP-DD
    - cd ${CI_PROJECT_DIR}/builds/MIP-DD
    - export CFLAGS="-Werror"
    - export CXXFLAGS="-Werror"
    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib

"soplex double debug":
  stage: build
  needs: [setup]
  variables:
    NAME: soplex_double_debug
  script:
    - cd ${MIPDD_DIR}
    - mkdir ${NAME}
    - cd ${NAME}
    - cmake ${CI_PROJECT_DIR} -DCMAKE_BUILD_TYPE=Debug -DBUGGER_ARITHMETIC=d -DSOPLEX_DIR=${SOPLEX_DIR}
    - make -j$(nproc)
    - bin/bugger --help

"soplex double optimized":
  stage: build
  needs: [setup]
  variables:
    NAME: soplex_double_optimized
  script:
    - cd ${MIPDD_DIR}
    - mkdir ${NAME}
    - cd ${NAME}
    - cmake ${CI_PROJECT_DIR} -DCMAKE_BUILD_TYPE=Release -DBUGGER_ARITHMETIC=d -DSOPLEX_DIR=${SOPLEX_DIR}
    - make -j$(nproc)
    - bin/bugger --help

"soplex rational debug":
  stage: build
  needs: [setup]
  variables:
    NAME: soplex_rational_debug
  script:
    - cd ${MIPDD_DIR}
    - mkdir ${NAME}
    - cd ${NAME}
    - cmake ${CI_PROJECT_DIR} -DCMAKE_BUILD_TYPE=Debug -DBUGGER_ARITHMETIC=r -DSOPLEX_DIR=${SOPLEX_DIR}
    - make -j$(nproc)
    - bin/bugger --help

"soplex rational optimized":
  stage: build
  needs: [setup]
  variables:
    NAME: soplex_rational_optimized
  script:
    - cd ${MIPDD_DIR}
    - mkdir ${NAME}
    - cd ${NAME}
    - cmake ${CI_PROJECT_DIR} -DCMAKE_BUILD_TYPE=Release -DBUGGER_ARITHMETIC=r -DSOPLEX_DIR=${SOPLEX_DIR}
    - make -j$(nproc)
    - bin/bugger --help

"scip double debug":
  stage: build
  needs: [setup]
  variables:
    NAME: scip_double_debug
  script:
    - cd ${MIPDD_DIR}
    - mkdir ${NAME}
    - cd ${NAME}
    - cmake ${CI_PROJECT_DIR} -DCMAKE_BUILD_TYPE=Debug -DBUGGER_ARITHMETIC=d -DSCIP_DIR=${SCIP_DIR}
    - make -j$(nproc)
    - bin/bugger --help

"scip double optimized":
  stage: build
  needs: [setup]
  variables:
    NAME: scip_double_optimized
  script:
    - cd ${MIPDD_DIR}
    - mkdir ${NAME}
    - cd ${NAME}
    - cmake ${CI_PROJECT_DIR} -DCMAKE_BUILD_TYPE=Release -DBUGGER_ARITHMETIC=d -DSCIP_DIR=/${SCIP_DIR}
    - make -j$(nproc)
    - bin/bugger --help

"scip rational debug":
  stage: build
  needs: [setup]
  variables:
    NAME: scip_rational_debug
  script:
    - cd ${MIPDD_DIR}
    - mkdir ${NAME}
    - cd ${NAME}
    - cmake ${CI_PROJECT_DIR} -DCMAKE_BUILD_TYPE=Debug -DBUGGER_ARITHMETIC=r -DSCIP_DIR=${SCIP_DIR}
    - make -j$(nproc)
    - bin/bugger --help

"scip rational optimized":
  stage: build
  needs: [setup]
  variables:
    NAME: scip_rational_optimized
  script:
    - cd ${MIPDD_DIR}
    - mkdir ${NAME}
    - cd ${NAME}
    - cmake ${CI_PROJECT_DIR} -DCMAKE_BUILD_TYPE=Release -DBUGGER_ARITHMETIC=r -DSCIP_DIR=${SCIP_DIR}
    - make -j$(nproc)
    - bin/bugger --help
