variables:
  PAPILO_VERSION: 2.2.1
  SOPLEX_REVISION: release-700
  SCIP_REVISION: v900

stages:
  - test

.ctest:
  stage: test
  image:
    name: gcc:10
  tags:
    - compile
  before_script:
    - apt-get update
    - apt-get install -y cmake libtbb-dev libblas-dev
  script:
    # download, build and install boost
    - wget https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION}/source/boost_$(echo ${BOOST_VERSION} | tr . _).tar.gz
    - tar -xzf boost_$(echo ${BOOST_VERSION} | tr . _).tar.gz
    - cd boost_$(echo ${BOOST_VERSION} | tr . _)
    - ./bootstrap.sh --with-libraries=program_options,serialization,iostreams,regex
    - ./b2 -j6 install

    # clone, build and install soplex
    - git clone https://github.com/scipopt/soplex.git ${CI_PROJECT_DIR}/soplex
    - cd ${CI_PROJECT_DIR}/soplex && git checkout ${SOPLEX_REVISION}
    - mkdir -p $CI_PROJECT_DIR/soplex/build
    - cd $CI_PROJECT_DIR/soplex/build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make -j && make install

    # clone, build and install scip
    - git clone https://github.com/scipopt/scip.git ${CI_PROJECT_DIR}/scip
    - cd ${CI_PROJECT_DIR}/scip && git checkout ${SCIP_REVISION}
    - mkdir -p $CI_PROJECT_DIR/scip/build
    - cd $CI_PROJECT_DIR/scip/build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DZIMPL=off -DREADLINE=off -DGMP=off -DPAPILO=off -DIPOPT=off
    - make -j && make install

    - mkdir -p $CI_PROJECT_DIR/builds/MIP-DD
    - cd $CI_PROJECT_DIR/builds/MIP-DD
    - export CFLAGS="-Werror"
    - export CXXFLAGS="-Werror"
    - cmake $CI_PROJECT_DIR ${CMAKE_FLAGS} -DBLA_STATIC=ON
    - make -j6
    - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

"ctest release":
  extends: .ctest
  variables:
    CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=Release"
    BOOST_VERSION: 1.65.0

"ctest debug":
  extends: .ctest
  variables:
    CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=Debug"
    BOOST_VERSION: 1.65.0
